export const COLORS = {
  primary: '#2E7D5B',
  background: '#F7F6F2',
  card: '#FFFFFF',
  textPrimary: '#14181F',
  textSecondary: '#5D6B7A',
  textOnPrimary: '#FFFFFF',
  surface: '#EFF3F0',
  border: '#DADFE3',
  shadow: '#14181F',
  warning: '#C97A2B',
  success: '#2E7D5B',
  danger: '#B3261E',
  primaryDark: '#1F5F45',
  primarySoft: '#E7F2EC',
  elevated: '#FCFDFB',
  muted: '#F0EFEA',
  onPrimarySoft: '#E2EFE7',
  onPrimaryMuted: '#BFD6C8',
  successLight: '#8DD3AA',
} as const;
